.TH sendbt 0 "Nov 11, 2015" "1.0"
.SH NAME
sendbt - my modified XINU send function for timed blocking message send
.SH DESCRIPTION
.B sendbt
functions almost equivalent to XINU's built in send function but allows the user to supply an additional field called maxwait which will allow the user to set the lifetime of the message they want to send